Repository ArkEcosystem/php-client, pull requests merged in 2019-09, with the labels that each got.

#63 feat: crypto endpoint
  src/API/Node.php
  tests/API/NodeTest.php
Labels: Bounty: Tier 4, Complexity: Low, Status: Contributor Approved, Type: Feature

#58 fix: fix node/fees query string
  src/API/Node.php
Labels: Complexity: Low, Type: Bugfix

#66 feat: add missing api endpoints
  src/API/Rounds.php
  src/API/Transactions.php
  tests/API/RoundsTest.php
  tests/API/TransactionsTest.php
Labels: Complexity: Medium, Status: Contributor Approved, Type: Feature

#68 ci: adjust job triggers
  .github/workflows/test.yml
Labels: Complexity: Low

#69 ci: report coverage to codecov
  .github/workflows/test.yml
Labels: Complexity: Low
