Repository ArkEcosystem/php-client, pull requests merged in 2019-05, with the labels that each got.

#42 feat: add node/fees endpoint
  src/API/Node.php
  tests/API/NodeTest.php
Labels: Bounty: Tier 4, Complexity: Low, Status: Contributor Approved, Type: Feature

#45 chore: update contribution link
  .github/CONTRIBUTING.md
  .github/PULL_REQUEST_TEMPLATE.md
Labels: Bounty: Tier 6, Complexity: Low, Status: Contributor Approved, Type: Task

#47 chore: update sdk url
  README.md
Labels: Bounty: Tier 6, Complexity: Low, Status: Contributor Approved, Type: Task

#48 chore: use organization-wide GitHub Configuration
  .github/CODE_OF_CONDUCT.md
  .github/CONTRIBUTING.md
  .github/ISSUE_TEMPLATE/Bug_report.md
  .github/ISSUE_TEMPLATE/Feature_request.md
  .github/PULL_REQUEST_TEMPLATE.md
Labels: Complexity: Medium, Type: Task

#49 chore: add itsanametoo to code owners
  CODEOWNERS
Labels: Complexity: Low, Type: Task
