Repository ArkEcosystem/php-client, pull requests merged in 2020-03, with the labels that each got.

#87 chore: add support for laravel 7
  composer.json
Labels: Complexity: Low, Type: Task

#88 ci: use stefanzweifel/git-auto-commit-action@v4.0.0
  .github/workflows/format.yml
Labels: Complexity: Low

#84 feat: add methods for first and last block
  src/API/Blocks.php
  tests/API/BlocksTest.php
Labels: Bounty: Tier 4, Complexity: Low, Status: Contributor Approved, Type: Feature
